pref("extensions.addon@sfdccrutch.org.description", "chrome://sfdccrutch/locale/strings.properties");  
pref("extensions.sfdccrutch.log", true);
pref("extensions.sfdccrutch.version","");
pref("extensions.sfdccrutch.loglevel", 1);
pref("extensions.sfdccrutch.clearlogfileatstarttime", true);
pref("extensions.sfdccrutch.sound", "default");
pref("extensions.sfdccrutch.installdir", "");
pref("extensions.sfdccrutch.template.action","Actions Completed Since Last Update and New Action:\n---------------------------------------------------------------------------\nTBC\n---------------------------------------------------------------------------\n[Owner:]\n[Next Update Date: ]");
pref("extensions.sfdccrutch.template.assignment","Dear %contactName,\nI am the GTS engineer working your case.\n%signature");
pref("extensions.sfdccrutch.template.signature","%user - Genband Technical Support (GTS)");
pref("extensions.sfdccrutch.dayinc.major",3);
pref("extensions.sfdccrutch.dayinc.BC",1);
pref("extensions.sfdccrutch.dayinc.minor",7);
pref("extensions.sfdccrutch.alarm.daysbefore.major",1);
pref("extensions.sfdccrutch.alarm.daysbefore.BC",1);
pref("extensions.sfdccrutch.alarm.daysbefore.minor",2);
pref("extensions.sfdccrutch.dayinc.weekdays","M-F");
pref("extensions.sfdccrutch.template.screening.default","Dear Customer,\nYour submission has been received by Genband Technical Support. You will be contacted by a technical resource to progress on the issue.");
pref("extensions.sfdccrutch.template.screening.requestInfo","Dear Customer,\nYour submission has been received by Genband Technical Support. You will be contacted by a technical resource to progress on the issue.\nIn the meantime, please provide the following information:\n");
pref("extensions.sfdccrutch.activated", true);
pref("extensions.sfdccrutch.maxAttachments", 1000);
pref("extensions.sfdccrutch.useOneTab",true);
pref("extensions.sfdccrutch.user","new");
pref("extensions.sfdccrutch.template.emailsubject","This concerns case %caseNumber %subject");
pref("extensions.sfdccrutch.pollingCaseNewCommentTimerMn",15);
pref("extensions.sfdccrutch.autoLogin",false);
pref("extensions.sfdccrutch.lightDisplay",false);
pref("extensions.sfdccrutch.autoSubscribeWhenGTSinterfaceCIisChecked",true);
pref("extensions.sfdccrutch.domainsToIntercept","spidrsfdc.genband.com");